---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Based on AWS Sample Template EC2InstanceWithSecurityGroupSample.
  Create an EC2 instance running the Amazon Linux AMI. The AMI is chosen based
  on the region in which the stack is run. This example creates an EC2 security group
  for the instance to give you SSH access.'

# Parameters (these are what you pass in)
# For paramaters with defaults, you do not need to provide an input. If they don't have a default, you need to pass a value in
Parameters:

  RegionId: # It looks like the default execution region can be referenced using AWS::Region
    Description: Targeted region for deployment
    Type: String
    AllowedValues:
      - "us-east-1"
      - "us-west-2"
    ConstraintDescription: must be a valid primary region in the U.S.

  VpcIdParm:
    Description: VPC ID for targeted VPC
    Type: String

  SubnetId:
    Description: Public Subnet to deploy the public EC2 instance to
    Type: String

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    Default: "aws_salmoncow"
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
    - t2.micro
    ConstraintDescription: must be a t2.micro EC2 instance type.

  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

# Mappings

  # - Fn::FindInMap:         (Function FindInMap...)
  #   - AWSInstanceType2Arch (Mapping name)
  #   - Ref: InstanceType    (Key feference in the map)
  #   - Arch                 (Value reference in the map)

Mappings:

  AWSInstanceType2Arch:
    t2.micro:
      Arch: HVM64

  AWSRegionArch2AMI:
    us-east-1:
      HVM64: ami-0fc61db8544a617ed


# Resources    
Resources:

  # EC2 instance
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType:
        Ref: InstanceType
      SubnetId:
        Ref: SubnetId
      SecurityGroupIds:
      - Ref: BaseSG
      KeyName:
        Ref: KeyName
      ImageId: 
        Fn::FindInMap:
        - AWSRegionArch2AMI
        - Ref: AWS::Region
        - Fn::FindInMap:
          - AWSInstanceType2Arch
          - Ref: InstanceType
          - Arch

  # SG
  BaseSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      VpcId:
        Ref: VpcIdParm
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp:
          Ref: SSHLocation

# Outputs
Outputs:

  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value:
      Ref: EC2Instance

  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value:
      Fn::GetAtt:
      - EC2Instance
      - AvailabilityZone

  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value:
      Fn::GetAtt:
      - EC2Instance
      - PublicDnsName
      
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value:
      Fn::GetAtt:
      - EC2Instance
      - PublicIp
